package provisioning

import (
	"errors"
	"time"

	"github.com/Abraxas-365/iamkit/internal/identity"
)

type Principal struct {
	ID           identity.CredentialID
	Environment  identity.EnvironmentID
	Organization identity.OrganizationID
	Connection   identity.ConnectionID
	// MapPhone maps SCIM phoneNumbers[type eq "mobile"] to the user's phone
	// (the connection's map_phone opt-in).
	MapPhone bool
}

// Anchor provenance of a provisioned identity's externalId.
const (
	// AnchorClient is an externalId supplied by the directory; immutable.
	AnchorClient = "client"
	// AnchorDerived is generated by IAMKit when the directory omitted
	// externalId; it is not exposed and may be upgraded once to a client value.
	AnchorDerived = "derived"
)

// Email is a secondary address a directory reports for its identity (SCIM
// emails[] minus userName). Aliases are scoped to the provisioning connection.
type Email struct {
	Value string `json:"value"`
	Type  string `json:"type,omitempty"`
}

type User struct {
	ID             identity.UserID `db:"id"`
	Email          string          `db:"email"`
	Name           string          `db:"name"`
	External       string          `db:"external_id"`
	ExternalSource string          `db:"external_id_source"`
	Manager        string          `db:"manager_id"`
	// Phone is the user's number (E.164, "" none); read and written only
	// when Principal.MapPhone.
	Phone    string    `db:"phone"`
	Active   bool      `db:"active"`
	Aliases  []Email   `db:"-"`
	Created  time.Time `db:"created_at"`
	Modified time.Time `db:"updated_at"`
	// Version increases on every change; used for optimistic concurrency.
	Version int64 `db:"version"`
}

// Update carries SCIM changes. Nil pointers leave the field untouched.
type Update struct {
	Name     *string
	Active   *bool
	Manager  *string
	Email    *string  // new primary address (userName)
	External *string  // accepted only when unchanged or upgrading a derived anchor
	Aliases  *[]Email // replace-set of this connection's aliases
	// Phone sets the mobile number ("" clears it); ignored without
	// Principal.MapPhone. A number that is not E.164 is ignored.
	Phone *string
	// IfVersion makes the update conditional on the identity's current
	// version (read-modify-write PATCH); a mismatch fails with ErrStale.
	IfVersion *int64
}

// ErrStale reports a conditional update whose IfVersion no longer matches.
var ErrStale = errors.New("provisioned identity modified concurrently")

// MaxResults is the SCIM list page cap advertised in ServiceProviderConfig.
const MaxResults = 100

// Filter is a SCIM list query. Field is one of "", "userName", "externalId",
// "emails.value" or "id".
type Filter struct {
	Field, Value string
	Start, Count int
}

// Clamped applies RFC 7644 §3.4.2.4: startIndex < 1 is treated as 1, a
// negative count as 0, and count is capped at MaxResults.
func (f Filter) Clamped() Filter {
	if f.Start < 1 {
		f.Start = 1
	}
	if f.Count < 0 {
		f.Count = 0
	}
	if f.Count > MaxResults {
		f.Count = MaxResults
	}
	return f
}
