package server

import (
	"github.com/Abraxas-365/iamkit/api"
	"github.com/gofiber/fiber/v2"
)

// openAPI serves the OpenAPI 3.1 document (api/openapi.json, generated by
// make openapi). It describes the API, so it is public like discovery.
func openAPI(c *fiber.Ctx) error {
	c.Set("Cache-Control", "public, max-age=300")
	c.Set(fiber.HeaderAccessControlAllowOrigin, "*")
	c.Set(fiber.HeaderContentType, fiber.MIMEApplicationJSON)
	return c.Send(api.Spec)
}
