-- Machine user keys (RFC 7523 JWT-bearer grant). The key's id is the kid
-- of the assertions it signs; IAMKit keeps only the public JWK (a key
-- generated by IAMKit hands its private half out once).
CREATE TABLE user_keys (
    id             uuid        PRIMARY KEY,
    environment_id uuid        NOT NULL,
    user_id        uuid        NOT NULL,
    public_jwk     jsonb       NOT NULL,
    expires_at     timestamptz NOT NULL,
    last_used_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, environment_id),
    FOREIGN KEY (user_id, environment_id) REFERENCES users(id, environment_id) ON DELETE CASCADE
);
CREATE INDEX user_keys_user ON user_keys(environment_id, user_id, created_at DESC);

-- Sessions opened with a key are revoked when the key is removed (userpg),
-- then keep their history without it.
ALTER TABLE sessions
    ADD COLUMN user_key_id uuid REFERENCES user_keys(id) ON DELETE SET NULL;
CREATE INDEX sessions_user_key ON sessions(user_key_id) WHERE user_key_id IS NOT NULL;
