package openapigen

import (
	"go/ast"
	"go/constant"
	"go/token"
	"go/types"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const fiberPkg = "github.com/gofiber/fiber/v2"
const httpxPkg = "github.com/Abraxas-365/iamkit/internal/httpx"

// Response is one documented answer of an operation. Schema nil means a
// body that is not JSON-typed (raw bytes, HTML, a redirect).
type Response struct {
	Status      int // 0 = status chosen at run time (documented as default)
	ContentType string
	Schema      map[string]any
}

// Operation is what the analyser learned about one handler.
type Operation struct {
	Summary     string
	Body        map[string]any // JSON request body
	Form        []string       // form fields (FormValue)
	Query       map[string]string
	Responses   []Response
	Open        bool // the handler answers through code the analyser cannot follow
	Unresolved  bool // the handler itself was not found
	ContentType string
}

// Analyzer reads handler source with go/types.
type Analyzer struct {
	pkgs     []*packages.Package
	funcs    map[string]*funcSource // "pkg.Func" / "pkg.(*T).M" → declaration
	lits     map[string]*funcSource // "file:line" → literal
	byObj    map[types.Object]*funcSource
	schemas  *schemas
	fiberCtx types.Type
}

type funcSource struct {
	pkg  *packages.Package
	decl *ast.FuncDecl
	lit  *ast.FuncLit
	doc  string
}

func (f *funcSource) params() *ast.FieldList {
	if f.decl != nil {
		return f.decl.Type.Params
	}
	return f.lit.Type.Params
}

func (f *funcSource) body() *ast.BlockStmt {
	if f.decl != nil {
		return f.decl.Body
	}
	return f.lit.Body
}

// Load parses and type-checks the module's internal packages from dir.
func Load(dir string) (*Analyzer, error) {
	cfg := &packages.Config{Dir: dir, Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports | packages.NeedDeps}
	pkgs, err := packages.Load(cfg, "./internal/...")
	if err != nil {
		return nil, err
	}
	a := &Analyzer{pkgs: pkgs, funcs: map[string]*funcSource{}, lits: map[string]*funcSource{}, byObj: map[types.Object]*funcSource{}, schemas: newSchemas()}
	for _, p := range pkgs {
		if len(p.Errors) > 0 {
			return nil, p.Errors[0]
		}
		for _, file := range p.Syntax {
			for _, d := range file.Decls {
				fn, ok := d.(*ast.FuncDecl)
				if !ok || fn.Body == nil {
					continue
				}
				src := &funcSource{pkg: p, decl: fn, doc: fn.Doc.Text()}
				a.funcs[declName(p.PkgPath, fn)] = src
				if obj := p.TypesInfo.Defs[fn.Name]; obj != nil {
					a.byObj[obj] = src
				}
				doc := fn.Doc.Text()
				ast.Inspect(fn.Body, func(n ast.Node) bool {
					if lit, ok := n.(*ast.FuncLit); ok {
						pos := p.Fset.Position(lit.Pos())
						key := filepath.Clean(pos.Filename) + ":" + itoa(pos.Line)
						if _, seen := a.lits[key]; !seen {
							a.lits[key] = &funcSource{pkg: p, lit: lit, doc: doc}
						}
					}
					return true
				})
			}
		}
		if p.PkgPath == "github.com/Abraxas-365/iamkit/internal/server" {
			for _, imp := range p.Types.Imports() {
				if imp.Path() == fiberPkg {
					a.fiberCtx = types.NewPointer(imp.Scope().Lookup("Ctx").Type())
				}
			}
		}
	}
	return a, nil
}

func itoa(n int) string { return constant.MakeInt64(int64(n)).ExactString() }

func declName(pkg string, fn *ast.FuncDecl) string {
	if fn.Recv == nil || len(fn.Recv.List) == 0 {
		return pkg + "." + fn.Name.Name
	}
	t := fn.Recv.List[0].Type
	star := false
	if s, ok := t.(*ast.StarExpr); ok {
		t, star = s.X, true
	}
	if idx, ok := t.(*ast.IndexExpr); ok {
		t = idx.X
	}
	name := t.(*ast.Ident).Name
	if star {
		return pkg + ".(*" + name + ")." + fn.Name.Name
	}
	return pkg + "." + name + "." + fn.Name.Name
}

// Find locates a handler from its runtime name and source position.
func (a *Analyzer) Find(name, file string, line int) *funcSource {
	if strings.Contains(name, ".func") || strings.HasSuffix(name, "-fm") && file != "<autogenerated>" {
		if src, ok := a.lits[filepath.Clean(file)+":"+itoa(line)]; ok {
			return src
		}
	}
	return a.funcs[strings.TrimSuffix(name, "-fm")]
}

// Analyze inspects one handler.
func (a *Analyzer) Analyze(src *funcSource) Operation {
	op := Operation{Query: map[string]string{}}
	if src == nil {
		op.Unresolved, op.Open = true, true
		return op
	}
	op.Summary = summary(src.doc)
	ctx := a.ctxParam(src)
	if ctx == nil {
		op.Open = true
		return op
	}
	w := &walker{a: a, op: &op, seen: map[*funcSource]bool{}}
	w.function(src, ctx, frame{}, 0)
	return op
}

func summary(doc string) string {
	doc = strings.TrimSpace(strings.Join(strings.Fields(doc), " "))
	if doc == "" {
		return ""
	}
	if i := strings.Index(doc, ". "); i > 0 {
		doc = doc[:i+1]
	}
	if len(doc) > 200 {
		doc = doc[:197] + "..."
	}
	return doc
}

func (a *Analyzer) ctxParam(src *funcSource) *types.Var {
	for _, field := range src.params().List {
		for _, name := range field.Names {
			if v, ok := src.pkg.TypesInfo.Defs[name].(*types.Var); ok && a.isCtx(v.Type()) {
				return v
			}
		}
	}
	return nil
}

func (a *Analyzer) isCtx(t types.Type) bool {
	p, ok := t.(*types.Pointer)
	if !ok {
		return false
	}
	n, ok := p.Elem().(*types.Named)
	return ok && n.Obj().Name() == "Ctx" && n.Obj().Pkg() != nil && n.Obj().Pkg().Path() == fiberPkg
}

// unknownType marks a raw body whose Content-Type the analyser cannot tell.
const unknownType = "?"

type walker struct {
	a    *Analyzer
	op   *Operation
	seen map[*funcSource]bool
	// contentType is the last Content-Type the handler set (raw sends).
	contentType string
}

// frame carries what a call site knows about a helper's parameters: integer
// constants (status codes) and functions passed as values (issue callbacks).
type frame struct {
	consts map[*types.Var]constant.Value
	fns    map[*types.Var]*funcSource
}

// function walks src where ctx is the request.
func (w *walker) function(src *funcSource, ctx *types.Var, consts frame, depth int) {
	if w.seen[src] || depth > 5 {
		return
	}
	w.seen[src] = true
	defer delete(w.seen, src)
	// A Content-Type set in a helper applies to its own sends only.
	defer func(ct string) { w.contentType = ct }(w.contentType)
	info := src.pkg.TypesInfo
	ast.Inspect(src.body(), func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.FuncLit:
			return true
		case *ast.ReturnStmt:
			for _, r := range x.Results {
				if call, ok := ast.Unparen(r).(*ast.CallExpr); ok && w.passesCtx(info, call, ctx) && w.callee(info, call, consts) == nil && !w.ctxMethod(info, call, ctx) {
					w.op.Open = true
				}
			}
		case *ast.CallExpr:
			w.call(src, info, x, ctx, consts, depth)
		}
		return true
	})
}

func (w *walker) isCtxExpr(info *types.Info, e ast.Expr, ctx *types.Var) bool {
	id, ok := ast.Unparen(e).(*ast.Ident)
	return ok && info.Uses[id] == ctx
}

func (w *walker) ctxMethod(info *types.Info, call *ast.CallExpr, ctx *types.Var) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	if w.isCtxExpr(info, sel.X, ctx) {
		return true
	}
	if inner, ok := sel.X.(*ast.CallExpr); ok {
		return w.ctxMethod(info, inner, ctx)
	}
	return false
}

func (w *walker) passesCtx(info *types.Info, call *ast.CallExpr, ctx *types.Var) bool {
	for _, arg := range call.Args {
		if w.isCtxExpr(info, arg, ctx) {
			return true
		}
	}
	return false
}

func (w *walker) callee(info *types.Info, call *ast.CallExpr, f frame) *funcSource {
	if id, ok := call.Fun.(*ast.Ident); ok {
		if v, ok := info.Uses[id].(*types.Var); ok {
			return f.fns[v]
		}
	}
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
		if s, ok := info.Selections[sel]; ok && s.Kind() == types.FieldVal {
			return w.a.funcs[Bindings[fieldName(s)]]
		}
	}
	return w.function_(info, call.Fun)
}

// Bindings names the functions the composition root assigns to
// function-typed handler fields ("pkg.Type.field" → declaration).
var Bindings = map[string]string{
	"github.com/Abraxas-365/iamkit/internal/iam/authentication/adapters/authhttp.Handler.issue": "github.com/Abraxas-365/iamkit/internal/server.(*Server).IssueSession",
	"github.com/Abraxas-365/iamkit/internal/iam/federation/adapters/fedhttp.Handler.respond":    "github.com/Abraxas-365/iamkit/internal/server.(*Server).RespondLogin",
	"github.com/Abraxas-365/iamkit/internal/iam/federation/adapters/fedhttp.Handler.hosted":     "github.com/Abraxas-365/iamkit/internal/iam/hosted/adapters/hostedhttp.(*Handler).Federated",
	// The OAuth side of bootstrap's finisher (SAML tickets render a form).
	"github.com/Abraxas-365/iamkit/internal/iam/hosted/adapters/hostedhttp.Handler.finish": "github.com/Abraxas-365/iamkit/internal/iam/oauth/adapters/oauthhttp.(*Handler).Finish",
}

func fieldName(s *types.Selection) string {
	recv := s.Recv()
	if p, ok := recv.(*types.Pointer); ok {
		recv = p.Elem()
	}
	named, ok := recv.(*types.Named)
	if !ok || named.Obj().Pkg() == nil {
		return ""
	}
	return named.Obj().Pkg().Path() + "." + named.Obj().Name() + "." + s.Obj().Name()
}

// function_ resolves an expression naming a declared function or method.
func (w *walker) function_(info *types.Info, e ast.Expr) *funcSource {
	var id *ast.Ident
	switch f := ast.Unparen(e).(type) {
	case *ast.Ident:
		id = f
	case *ast.SelectorExpr:
		id = f.Sel
	case *ast.IndexExpr:
		if s, ok := f.X.(*ast.Ident); ok {
			id = s
		}
	}
	if id == nil {
		return nil
	}
	obj := info.Uses[id]
	if fn, ok := obj.(*types.Func); ok {
		obj = fn.Origin()
	}
	return w.a.byObj[obj]
}

func (w *walker) intValue(info *types.Info, e ast.Expr, f frame) (int, bool) {
	if tv, ok := info.Types[e]; ok && tv.Value != nil && tv.Value.Kind() == constant.Int {
		if v, ok := constant.Int64Val(tv.Value); ok {
			return int(v), true
		}
	}
	if id, ok := ast.Unparen(e).(*ast.Ident); ok {
		if v, ok := info.Uses[id].(*types.Var); ok {
			if c, ok := f.consts[v]; ok {
				if n, ok := constant.Int64Val(c); ok {
					return int(n), true
				}
			}
		}
	}
	return 0, false
}

func (w *walker) stringValue(info *types.Info, e ast.Expr) (string, bool) {
	if tv, ok := info.Types[e]; ok && tv.Value != nil && tv.Value.Kind() == constant.String {
		return constant.StringVal(tv.Value), true
	}
	return "", false
}

func (w *walker) call(src *funcSource, info *types.Info, call *ast.CallExpr, ctx *types.Var, consts frame, depth int) {
	// Package helpers that read the request.
	if fn, ok := info.Uses[selName(call.Fun)].(*types.Func); ok && fn.Pkg() != nil && fn.Pkg().Path() == httpxPkg && fn.Name() == "PaginationFromCtx" {
		w.op.Query["limit"], w.op.Query["offset"], w.op.Query["search"] = "integer", "integer", "string"
		return
	}
	sel, ok := call.Fun.(*ast.SelectorExpr)
	// Raw query arguments: c.Context().QueryArgs().Peek/PeekMulti("name").
	if ok && (sel.Sel.Name == "Peek" || sel.Sel.Name == "PeekMulti") && len(call.Args) == 1 {
		if args, isCall := sel.X.(*ast.CallExpr); isCall {
			if as, isSel := args.Fun.(*ast.SelectorExpr); isSel && as.Sel.Name == "QueryArgs" && w.ctxMethod(info, args, ctx) {
				if name, known := w.stringValue(info, call.Args[0]); known {
					if _, exists := w.op.Query[name]; !exists {
						w.op.Query[name] = "string"
					}
				}
				return
			}
		}
	}
	if ok && sel.Sel.Name == "SetBodyStreamWriter" && w.ctxMethod(info, call, ctx) {
		w.op.Responses = append(w.op.Responses, Response{Status: 200, ContentType: w.contentType})
		return
	}
	if ok && (w.isCtxExpr(info, sel.X, ctx) || isStatusChain(info, sel.X, w, ctx)) {
		status, statusKnown := 200, true
		if inner, ok := sel.X.(*ast.CallExpr); ok {
			status, statusKnown = w.intValue(info, inner.Args[0], consts)
		}
		if !statusKnown {
			status = 0
		}
		switch sel.Sel.Name {
		case "BodyParser":
			if len(call.Args) == 1 {
				if t := info.TypeOf(call.Args[0]); t != nil {
					if p, ok := t.(*types.Pointer); ok {
						w.op.Body = w.a.schemas.schema(p.Elem(), true)
					}
				}
			}
		case "JSON":
			ct := "application/json"
			if len(call.Args) > 1 {
				if s, ok := w.stringValue(info, call.Args[1]); ok {
					ct, _, _ = strings.Cut(s, ";")
				}
			}
			w.op.Responses = append(w.op.Responses, Response{Status: status, ContentType: ct, Schema: w.value(src, info, call.Args[0], 0)})
		case "SendStatus":
			if n, ok := w.intValue(info, call.Args[0], consts); ok {
				w.op.Responses = append(w.op.Responses, Response{Status: n})
			}
		case "Send", "SendString", "SendStream", "SendFile":
			w.op.Responses = append(w.op.Responses, Response{Status: status, ContentType: w.contentType})
		case "Set":
			name, ok := w.stringValue(info, call.Args[0])
			switch {
			case !ok:
				w.contentType = unknownType // headers copied from elsewhere
			case strings.EqualFold(name, "Content-Type"):
				w.contentType = unknownType
				if v, ok := w.stringValue(info, call.Args[1]); ok {
					w.contentType, _, _ = strings.Cut(v, ";")
				}
			}
		case "Type":
			if ext, ok := w.stringValue(info, call.Args[0]); ok {
				w.contentType = map[string]string{"txt": "text/plain", "json": "application/json", "html": "text/html"}[ext]
			}
		case "Redirect":
			code := 302
			if len(call.Args) > 1 {
				if n, ok := w.intValue(info, call.Args[1], consts); ok {
					code = n
				}
			}
			w.op.Responses = append(w.op.Responses, Response{Status: code})
		case "Query", "QueryInt", "QueryBool", "QueryFloat":
			if name, ok := w.stringValue(info, call.Args[0]); ok {
				kind := map[string]string{"Query": "string", "QueryInt": "integer", "QueryBool": "boolean", "QueryFloat": "number"}[sel.Sel.Name]
				if _, exists := w.op.Query[name]; !exists || kind != "string" {
					w.op.Query[name] = kind
				}
			}
		case "FormValue":
			if name, ok := w.stringValue(info, call.Args[0]); ok {
				w.op.Form = appendUnique(w.op.Form, name)
			}
		}
		return
	}
	// Helpers that receive the request: follow them.
	if !w.passesCtx(info, call, ctx) {
		return
	}
	target := w.callee(info, call, consts)
	if target == nil {
		return
	}
	inner := w.a.ctxParam(target)
	if inner == nil {
		return
	}
	next := frame{consts: map[*types.Var]constant.Value{}, fns: map[*types.Var]*funcSource{}}
	params := paramVars(target)
	for i, arg := range call.Args {
		if i >= len(params) {
			break
		}
		if n, ok := w.intValue(info, arg, consts); ok {
			next.consts[params[i]] = constant.MakeInt64(int64(n))
		}
		if fn := w.funcArg(src, info, arg, consts); fn != nil {
			next.fns[params[i]] = fn
		}
	}
	w.function(target, inner, next, depth+1)
}

// funcArg resolves a function passed as a value: a declared function or
// method value, a literal, or a function parameter known to the caller.
func (w *walker) funcArg(src *funcSource, info *types.Info, arg ast.Expr, f frame) *funcSource {
	arg = ast.Unparen(arg)
	if lit, ok := arg.(*ast.FuncLit); ok {
		return &funcSource{pkg: src.pkg, lit: lit, doc: src.doc}
	}
	if id, ok := arg.(*ast.Ident); ok {
		if v, ok := info.Uses[id].(*types.Var); ok {
			return f.fns[v]
		}
	}
	if _, ok := info.TypeOf(arg).Underlying().(*types.Signature); !ok {
		return nil
	}
	if sel, ok := arg.(*ast.SelectorExpr); ok {
		if s, ok := info.Selections[sel]; ok && s.Kind() == types.FieldVal {
			return w.a.funcs[Bindings[fieldName(s)]]
		}
	}
	return w.function_(info, arg)
}

func appendUnique(list []string, s string) []string {
	for _, v := range list {
		if v == s {
			return list
		}
	}
	return append(list, s)
}

func paramVars(src *funcSource) []*types.Var {
	var out []*types.Var
	for _, field := range src.params().List {
		for _, name := range field.Names {
			if v, ok := src.pkg.TypesInfo.Defs[name].(*types.Var); ok {
				out = append(out, v)
			}
		}
	}
	return out
}

func selName(e ast.Expr) *ast.Ident {
	switch f := e.(type) {
	case *ast.SelectorExpr:
		return f.Sel
	case *ast.Ident:
		return f
	}
	return nil
}

func isStatusChain(info *types.Info, e ast.Expr, w *walker, ctx *types.Var) bool {
	call, ok := e.(*ast.CallExpr)
	if !ok {
		return false
	}
	sel, ok := call.Fun.(*ast.SelectorExpr)
	return ok && sel.Sel.Name == "Status" && len(call.Args) == 1 && w.isCtxExpr(info, sel.X, ctx)
}

// value is the schema of a JSON-encoded expression; map literals are read
// key by key.
func (w *walker) value(src *funcSource, info *types.Info, e ast.Expr, depth int) map[string]any {
	e = ast.Unparen(e)
	if depth < 4 {
		if s := w.derived(src, info, e, depth); s != nil {
			return s
		}
	}
	if lit, ok := e.(*ast.CompositeLit); ok {
		if t := info.TypeOf(lit); t != nil {
			if m, ok := t.Underlying().(*types.Map); ok {
				if b, ok := m.Key().Underlying().(*types.Basic); ok && b.Info()&types.IsString != 0 {
					props := map[string]any{}
					var required []string
					for _, elt := range lit.Elts {
						kv, ok := elt.(*ast.KeyValueExpr)
						if !ok {
							continue
						}
						key, ok := w.stringValue(info, kv.Key)
						if !ok {
							return map[string]any{"type": "object"}
						}
						props[key] = w.value(src, info, kv.Value, depth)
						required = append(required, key)
					}
					out := map[string]any{"type": "object", "properties": props}
					if len(required) > 0 {
						out["required"] = sorted(required)
					}
					return out
				}
			}
			if s, ok := t.Underlying().(*types.Slice); ok {
				if _, isMap := s.Elem().Underlying().(*types.Map); isMap && len(lit.Elts) > 0 {
					return map[string]any{"type": "array", "items": map[string]any{"type": "object"}}
				}
			}
		}
	}
	if u, ok := e.(*ast.UnaryExpr); ok && u.Op == token.AND {
		if t := info.TypeOf(u.X); t != nil {
			return w.a.schemas.schema(t, false)
		}
	}
	t := info.TypeOf(e)
	if t == nil {
		return anyValue()
	}
	if tv := info.Types[e]; tv.IsNil() {
		return map[string]any{"type": "null"}
	}
	s := w.a.schemas.schema(t, false)
	// A non-nil literal slice or map is never null.
	if _, ok := e.(*ast.CompositeLit); ok {
		s = notNull(s)
	}
	return s
}

// derived follows a map built in a local variable (initializer plus
// out["key"] = … assignments, which are optional members) or returned by a
// helper.
func (w *walker) derived(src *funcSource, info *types.Info, e ast.Expr, depth int) map[string]any {
	t := info.TypeOf(e)
	if t == nil {
		return nil
	}
	if _, ok := t.Underlying().(*types.Map); !ok {
		return nil
	}
	switch x := e.(type) {
	case *ast.Ident:
		v, ok := info.Uses[x].(*types.Var)
		if !ok || v.IsField() || v.Parent() == nil || v.Parent() == v.Pkg().Scope() {
			return nil
		}
		var bases []map[string]any
		extra := map[string]any{}
		ast.Inspect(src.body(), func(n ast.Node) bool {
			as, ok := n.(*ast.AssignStmt)
			if !ok || len(as.Lhs) != len(as.Rhs) {
				return true
			}
			for i, lhs := range as.Lhs {
				switch l := lhs.(type) {
				case *ast.Ident:
					if info.Defs[l] == v || info.Uses[l] == v {
						bases = append(bases, w.value(src, info, as.Rhs[i], depth+1))
					}
				case *ast.IndexExpr:
					if id, ok := l.X.(*ast.Ident); ok && info.Uses[id] == v {
						if key, ok := w.stringValue(info, l.Index); ok {
							extra[key] = w.value(src, info, as.Rhs[i], depth+1)
						}
					}
				}
			}
			return true
		})
		if len(bases) == 0 {
			return nil
		}
		base := union(bases)
		if props, ok := base["properties"].(map[string]any); ok && len(extra) > 0 {
			merged := map[string]any{}
			for k, p := range props {
				merged[k] = p
			}
			for k, p := range extra {
				if _, exists := merged[k]; !exists {
					merged[k] = p
				}
			}
			base = clone(base)
			base["properties"] = merged
		}
		return base
	case *ast.CallExpr:
		target := w.function_(info, x.Fun)
		if target == nil {
			return nil
		}
		var results []map[string]any
		ast.Inspect(target.body(), func(n ast.Node) bool {
			if _, ok := n.(*ast.FuncLit); ok {
				return false
			}
			if r, ok := n.(*ast.ReturnStmt); ok && len(r.Results) == 1 {
				results = append(results, w.value(target, target.pkg.TypesInfo, r.Results[0], depth+1))
			}
			return true
		})
		if len(results) == 0 {
			return nil
		}
		return union(results)
	}
	return nil
}

func notNull(s map[string]any) map[string]any {
	if list, ok := s["type"].([]any); ok && len(list) == 2 && list[1] == "null" {
		out := clone(s)
		out["type"] = list[0]
		return out
	}
	return s
}

func sorted(list []string) []string {
	out := append([]string(nil), list...)
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j] < out[j-1]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}
