#!/usr/bin/env bash
# Creates <variant>/.env and <variant>/secrets/jwt.pem for a Compose
# deployment (variant: traefik or caddy). Never overwrites either: both hold
# secrets that must stay stable (a new signing key or HMAC secret invalidates
# every issued token; a new encryption key makes stored secrets unreadable).
#
#   deploy/compose/setup.sh traefik iam.example.com ops@example.com
set -euo pipefail

usage() {
  echo "usage: $0 <traefik|caddy> <domain> <acme-email>" >&2
  exit 2
}
[ $# -eq 3 ] || usage
variant=$1 domain=$2 email=$3
case $variant in traefik | caddy) ;; *) usage ;; esac
case $domain in "" | *[!A-Za-z0-9.-]*) echo "domain must be a host name (no scheme, port or path)" >&2; exit 2 ;; esac
case $email in *@*) ;; *) echo "acme-email must be an email address" >&2; exit 2 ;; esac
command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

dir=$(cd "$(dirname "$0")/$variant" && pwd)
if [ -e "$dir/.env" ] || [ -e "$dir/secrets/jwt.pem" ]; then
  echo "$dir/.env or secrets/jwt.pem already exists; not overwriting" >&2
  exit 1
fi

umask 077
mkdir -p "$dir/secrets"
openssl genrsa -out "$dir/secrets/jwt.pem" 4096 2>/dev/null
cat >"$dir/.env" <<EOF
# Generated by setup.sh. Back this file and secrets/jwt.pem up (privately):
# they cannot be regenerated without invalidating tokens and stored secrets.

# Public host name; the issuer is https://\$IAMKIT_DOMAIN. Point its DNS at
# this host and open ports 80 and 443 before the first start.
IAMKIT_DOMAIN=$domain
ACME_EMAIL=$email

# Pin a release (ghcr.io/abraxas-365/iamkit:<version>@sha256:...) in production.
IAMKIT_IMAGE=ghcr.io/abraxas-365/iamkit:latest

POSTGRES_PASSWORD=$(openssl rand -hex 24)
OIDC_HMAC_SECRET=$(openssl rand -hex 32)
IAMKIT_ENCRYPTION_KEY=$(openssl rand -base64 32)

# Optional services (Compose profiles). For Redis add "redis" and set
# REDIS_URL; for the OpenTelemetry collector add "otel" and set the endpoint.
COMPOSE_PROFILES=
# REDIS_URL=redis://redis:6379/0
# OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318

# Subnet of the proxy ↔ IAMKit network, the only addresses IAMKit trusts to
# name the client. Change it if it overlaps a network of this host.
# EDGE_SUBNET=10.89.250.0/24

# Every other IAMKit variable (docs/reference/configuration.md) can be added
# here: the iamkit container reads this file, e.g. EMAIL_PROVIDER, SMTP_*.
EOF
if [ "$variant" = traefik ]; then
  cat >>"$dir/.env" <<'EOF'

# ACME challenge: "http" (HTTP-01 on port 80) or "tls" (TLS-ALPN-01 on 443).
IAMKIT_ACME_CHALLENGE=http
EOF
fi
echo "wrote $dir/.env and $dir/secrets/jwt.pem"
echo "next: cd $dir && docker compose up -d --wait"
