// Package api embeds IAMKit's OpenAPI document (openapi.json, generated by
// make openapi from the server's routes and handlers).
package api

import _ "embed"

// Spec is the OpenAPI 3.1 document served at /openapi.json.
//
//go:embed openapi.json
var Spec []byte
